Reddit/config/routes.rb
Rails.application.routes.draw do

resources :users, only: [:new, :show, :create]
resource :session, only: [:new, :create, :destroy]
resources :subs

end

Reddit/app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, :sub_id, :author_id, presence: true

  
end

Reddit/app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :name, :description, :moderator_id, presence: true
  validates :name, uniqueness: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

end

Reddit/app/models/user.rb
class User < ActiveRecord::Base

  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token
  attr_reader :password

  has_many :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials (username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def ensure_session_token
     self.session_token ||= SecureRandom.urlsafe_base64(128)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(128)
    self.save!
  end

#
end

Reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def log_in(user)
    session[:session_token] = user.session_token
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    current_user
  end

  def check_login
    unless logged_in?
      flash[:errors] = ["Must be logged in!"]
      redirect_to new_user_url
    end
  end

end

Reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
            session_params[:username],
            session_params[:password]
    )
    if user
      log_in(user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["invalid username or password"]
      render :new
    end
  end

  def destroy
    log_out
    render :new
  end

  private

  def session_params
    params.require(:user).permit(:username, :password)
  end

end

Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
before_action :check_login, except: [:index, :show]
before_action :require_user_owns_sub!, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    # @sub = current_user.subs.new(sub_params)
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:name, :description)
  end

  def require_user_owns_sub!
    sub = Sub.find_by(id: params[:id])
    unless sub.moderator_id == current_user.id
      flash[:errors] = ["Must be moderator to edit"]
      redirect_to subs_url
    end
  end


end

Reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show
    if current_user.id == params[:id].to_i
      @user = current_user
      render :show
    else
      redirect_to new_user_url
    end
  end

private

  def user_params
    params.require(:user).permit(:username, :password)
  end


end

Reddit/app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type='hidden'
            name ='authenticity_token'
            value ='#{form_authenticity_token}'>".html_safe
  end
end

Reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

Reddit/app/helpers/subs_helper.rb
module SubsHelper
end

Reddit/app/helpers/users_helper.rb
module UsersHelper
end

Reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <% if current_user %>
  <%=  current_user.username %>
  <br>
  <%= button_to "logout", session_url, method: :delete %>
  <%  end  %>
</head>
<body>

<%= yield %>
<ul>
<% if flash[:errors] %>
  <% flash[:errors].each do |error|  %>
    <li>
    <%=   error %>
    </li>
    <% end %>
<% end %>
</ul>
</body>
</html>

Reddit/app/views/subs/_form.html.erb
<% method = (sub.persisted? ? "PATCH" : "POST") %>
<% action_url = (sub.persisted? ? sub_url(sub) : subs_url) %>




<form action="<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="sub_name">Sub Name</label>
  <input type="text" name="sub[name]" value="<%= sub.name %>" id="sub_name">

  <br>
  <br>

  <label for="description">Description</label>
  <input type="text" name="sub[description]" value="<%= sub.description %>" id="description">

  <br>
  <br>

  <input type="submit" value="submit">
  <%= auth_token %>
</form>

Reddit/app/views/subs/edit.html.erb
<h1> Edit Sub :-( </h1>
<%= render 'form', sub: @sub %>

Reddit/app/views/subs/index.html.erb
<h1> All the Subs! </h1>

<ul>
  <% @subs.each do |sub| %>
  <li> <%= link_to sub.name, sub_url(sub) %> </li>
  <% end %>
</ul>

Reddit/app/views/subs/new.html.erb
<h1> Create new Sub!!!!!! </h1>
<%= render 'form', sub: @sub %>

Reddit/app/views/subs/show.html.erb
<h1> Sub: <%= @sub.name %> </h1>
<h3> Moderator: <%= @sub.moderator.username %> </h3>
<p>  Description: <%= @sub.description %> </p>

Reddit/app/views/users/new.html.erb
<h1>Create New User</h1>

<form action= "<%= users_url %>" method="post">

<label for="username">Username</label>
<input type="text" name="user[username]" id="username">

<br>
<br>

<label for="password">Password</label>
<input type="text" name="user[password]" id="password">

<input type="submit" value="Create User">

<%= auth_token %>

</form>

Reddit/app/views/users/show.html.erb
<h1> <%= @user.username %></h1>